version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - rbialon
  ignore:
  - dependency-name: responses
    versions:
    - 0.13.0
    - 0.13.1
    - 0.13.2
  - dependency-name: marshmallow
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: pytest
    versions:
    - 6.2.2
