name: Python flake8 and tests

on: [push]

env:
  PIPENV_NOSPIN: 1

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Lint with flake8
        run: |
          python -m pip install flake8
          echo "::add-matcher::.github/flake8-error-matcher.json"
          echo "::add-matcher::.github/flake8-warning-matcher.json"
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv run python -m pytest
